### ISSUE TITLE
can gulp-rev-replace replace in jade?

### ISSUE THREAD

**Issue by YDSS** [jamesknelson/gulp-rev-replace#48] opened 2015-12-28 14:30 UTC
Hi, I'm using `gulp-rev-replace` for a while and it's fine, until I decide replace "plain html" with template. I found gulp-rev-replace can not replace path in jade, then I read doc and issues and got nothing useful. Does anyone has some advices?

**Comment by futuranna** [comment] 2016-06-22 20:52
You can add jade to the **replaceInExtensions**
```
gulp.src('src/**/*.jade')
        .pipe(revReplace({
            replaceInExtensions: ['.jade']
        }))
        .pipe(gulp.dest('dist'));
```

**Comment by adouglas** [comment] 2016-09-06 21:39
The above fix is correct, and this should be closed as not a bug

**Closed** 2017-02-04 09:53 UTC
